config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#index'

  resources :articles do
    resources :comments, only: [:new, :create]
  end

  resource :profile, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  content    :text             not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          not null
#
# Indexes
#
#  index_articles_on_user_id  (user_id)
#
class Article < ApplicationRecord
  validates :title, presence: true
  validates :title, length: { minimum: 2, maximum: 100 }
  validates :title, format: { with: /\A(?!\@)/ }

  validates :content, presence: true
  validates :content, length: { minimum: 10 }
  validates :content, uniqueness: true

  validate :validate_title_and_content_length

  has_many :comments, dependent: :destroy
  belongs_to :user

  def display_created_at
    I18n.l(self.created_at, format: :default)
  end

  def author_name
    user.display_name
  end

  private
  def validate_title_and_content_length
    char_count = self.title.length + self.content.length
    errors.add(:content, '50文字いじょうで！') unless char_count > 50
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  content    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  article_id :integer          not null
#
# Indexes
#
#  index_comments_on_article_id  (article_id)
#
class Comment < ApplicationRecord
  belongs_to :article
  validates :content, presence: true
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id           :integer          not null, primary key
#  birthday     :date
#  gender       :integer
#  introduction :text
#  nickname     :string
#  subscribed   :boolean          default(FALSE)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :integer          not null
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#
class Profile < ApplicationRecord
  enum gender: { male: 0, female: 1, other: 2 }
  belongs_to :user
  has_one_attached :avatar

  def age
    return '不明' unless birthday.present?
    years = Time.zone.now.year - birthday.year
    days = Time.zone.now.yday - birthday.yday

    if days < 0
      "#{years - 1}歳"
    else
      "#{years}歳"
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_one :profile, dependent: :destroy

  delegate :birthday, :age, :gender, to: :profile, allow_nil: true

  def has_written?(article)
    articles.exists?(id: article.id)
  end

  def display_name
    profile&.nickname || self.email.split('@').first
  end

  def prepare_profile
    profile || build_profile
  end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'default-avatar.png'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :detroy]
  def index
    @articles = Article.all
  end

  def show
    @comments = @article.comments
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to article_path(@article), notice: '保存できたよ'
    else
      flash.now[:error] = '保存に失敗しました'
      render :new
    end
  end

  def edit
    @article = current_user.articles.find(params[:id])
  end

  def update
    @article = current_user.articles.find(params[:id])
    if @article.update(article_params)
      redirect_to article_path(@article), notice: '更新できました'
    else
      flash.now[:error] = '更新に失敗しました'
      render :edit
    end
  end

  def destroy
    article = current_user.articles.find(params[:id])
    article.destroy!
    redirect_to root_path, notice: '削除に成功しました'
  end

  private
  def article_params
    params.require(:article).permit(:title, :content)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    article = Article.find(params[:article_id])
    @comment = article.comments.build
  end

  def create
    article = Article.find(params[:article_id])
    @comment = article.comments.build(comment_params)
    if @comment.save
      redirect_to article_path(article), notice: 'コメントを追加'
    else
      flash.now[:error] = '更新できませんでした'
      render :new
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  def show
    @profile = current_user.profile
  end

  def edit
    @profile = current_user.prepare_profile
  end

  def update
    @profile = current_user.prepare_profile
    @profile.assign_attributes(profile_params)
    if @profile.save
      redirect_to profile_path, notice: 'プロフィールを更新'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  private
  def profile_params
    params.require(:profile).permit(
      :nickname,
      :introduction,
      :gender,
      :birthday,
      :subscribed,
      :avatar
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.haml
.container
  %ul
    - article.errors.full_messages.each do |message|
      %li= message
  = form_with(model: article, local: true) do |f|
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content
    = f.submit '保存', class: 'btn-primary'

app/views/articles/_tabs.html.haml
.tabs
  .tabs_item.active
    新着記事一覧
  .tabs_item
    タイムライン

app/views/articles/edit.html.haml
= render 'form', article: @article

app/views/articles/index.html.haml
.container
  = render 'tabs'
  - @articles.each do |article|
    = render 'commons/article', article: article
  = link_to new_article_path do
    .float_btn
      %i.fa.fa-plus

app/views/articles/new.html.haml
= render 'form', article: @article

app/views/articles/show.html.haml
.article
  %h1.article_title= @article.title
  .article_detail
    = image_tag @article.user.avatar_image
    %div
      %p= @article.user.display_name
      %p= @article.display_created_at
    - if user_signed_in? && current_user.has_written?(@article)
      .article_detail_actions
        .dropdown
          = image_tag 'actions.svg', class: 'dropbtn'
          .dropdown-content.mini
            = link_to '編集する', edit_article_path(@article)
            = link_to '削除する', article_path(@article), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' }
  .article_content
    = @article.content
  .article_heart
    = image_tag 'heart.svg'

.article
  %h2 コメント一覧
  - @comments.each do |comment|
    .article_comment
      %p= comment.content

.container
  = link_to new_article_comment_path(@article) do
    .btn-secondary
      コメントを追加

app/views/comments/new.html.haml
.container
  %ul
    - @comment.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @comment, url: article_comments_path(@comment.article), local: true) do |f|
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content
    = f.submit '保存', class: 'btn-primary'

app/views/commons/_article.html.haml
= link_to article_path(article) do
  .card
    .card_image
      = image_tag 'eyecatch1.png'
    .card_content
      .card_title
        = article.title
      .card_heart
        = image_tag 'heart.svg'
        %span 23
      .card_detail
        = image_tag article.user.avatar_image
        %div
          %p= article.author_name
          %p= article.display_created_at

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BlogApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %link{:href => "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
  %body
    %header.header
      .header_logos
        - if !current_page?(root_path)
          = link_to :back do
            = image_tag 'back.svg', class: 'header_back'
        %p.header_pageTitle BlogApp
      - if user_signed_in?
        .dropdown
          = image_tag current_user.avatar_image, class: 'header_avatar dropbtn'
          .dropdown-content
            = link_to 'プロフィール', profile_path
            = link_to 'ログアウト', destroy_user_session_path, data: { method: 'delete' }
      - else
        = link_to 'ログイン', new_user_session_path, class: 'header_loginBtn'
    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{:class => key}= value
    = yield

app/views/profiles/edit.html.haml
.container
  %ul
    - @profile.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
    %div 
      = f.label :avatar, 'アバター'
    %div 
      = f.file_field :avatar
    %div
      = f.label :nickname, 'ハンドルネーム'
    %div
      = f.text_field :nickname, class: 'text'
    %div
      = f.label :introduction, '自己紹介'
    %div
      = f.text_area :introduction
    %div 
      = f.label :gender, '性別'
    %div 
      = f.select :gender, Profile.genders.map { |k, v| [I18n.t("enum.genders.#{k}"), k ] }, {}, { class: 'text' }
    %div 
      = f.label :birthday, '生年月日'
    %div 
      = f.date_field :birthday, class: 'text'
    %div 
      = f.label :subscribed, '通知を受け取る'
      = f.check_box :subscribed

    = f.submit '保存', class: 'btn-primary'

app/views/profiles/show.html.haml
.container.profilePage
  .profilePage_user
    .profilePage_user_image
      = image_tag current_user.avatar_image
    .profilePage_user_basicInfo
      .profilePage_user_name
        .profilePage_user_displayName
          #{current_user.display_name} (#{current_user.age}・#{I18n.t("enum.genders.#{current_user.gender}")})
        .profilePage_user_actionButton
          = link_to 'Edit', edit_profile_path
      .profilePage_user_introduction
        = current_user.profile&.introduction

-current_user.articles.each do |article|
  = render 'commons/article', article: article